# -*- coding: utf-8 -*-
"""Multiple Linear Regression (students.csv) (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ciz71EwqgDBP0XEGFC8WzbxfChL6DDLi
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from mpl_toolkits.mplot3d import Axes3D

df = pd.read_csv('student.csv')
df.head()

df.info()

df.describe()

sns.pairplot(df,diag_kind='kde')

x = df[['Math','Reading']].values
y = df['Writing'].values

math = df['Math'].values
read = df['Reading'].values
write = df['Writing'].values
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(math,read,write,color='orange')
plt.show()

import statsmodels.api as sm
reg_ols = sm.OLS(endog=y,exog=x).fit()
reg_ols.summary()

np.corrcoef(math,write)

np.corrcoef(math,read)

np.corrcoef(write,read)[0,1]

sns.heatmap(df.corr(),annot=True)

#VIF(multicollinearity) 
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

X = add_constant(df)

X.shape

X.values

pd.Series([variance_inflation_factor(X.values,i) for i in range(X.shape[1])],index=X.columns)

from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(x,y)
y_pred = reg.predict(x)

from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y,y_pred)
print('mse is :',mse)
print('rmse is :',np.sqrt(mse))

plt.figure(figsize=(12,8))
sns.residplot(y,y_pred,color='g')

reg.score(x,y)

def predi(x):
    predicted = reg.predict(x)
    return predicted

predi([[76,83]])

"""# Saving model using pickle"""

import pickle

filename = 'final_write.sav'

pickle.dump(reg,open(filename,'wb'))